services:
  inferline:
    image: cloudriftai/inferline-server:latest
    platform: linux/amd64
    expose:
      - "8000"
    environment:
      - HOST=0.0.0.0
    depends_on:
      - nginx-proxy
      - acme-companion
    networks:
      - proxy-network
    restart: unless-stopped

  frontend:
    image: cloudriftai/inferline-frontend:latest
    platform: linux/amd64
    expose:
      - "5000"
    environment:
      - API_BASE_URL=http://inferline:8000
      - FRONTEND_BASE_URL=https://inferline.cloudrift.ai
    depends_on:
      - inferline
    networks:
      - proxy-network
    restart: unless-stopped

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./nginx/inferline.conf:/etc/nginx/conf.d/inferline.conf:ro
    environment:
      - PROXY_READ_TIMEOUT=300
      - PROXY_CONNECT_TIMEOUT=300
      - PROXY_SEND_TIMEOUT=300
      - CLIENT_MAX_BODY_SIZE=10m
      - CLIENT_BODY_BUFFER_SIZE=128k
    restart: always
    labels:
      - "com.github.nginx-proxy.nginx"
    networks:
      - proxy-network

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - nginx_certs:/etc/nginx/certs:rw
      - nginx_vhost:/etc/nginx/vhost.d:rw
      - nginx_html:/usr/share/nginx/html:rw
    environment:
      - DEFAULT_EMAIL=admin@cloudrift.ai
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DOMAINS=inferline.cloudrift.ai
    depends_on:
      - nginx-proxy
    restart: always
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge

volumes:
  nginx_certs:
  nginx_vhost:
  nginx_html:
  acme:
